const BASE=100000,POOL=[["2330","台積電"],["2454","聯發科"],["2308","台達電"],["2382","廣達"],["3231","緯創"],["2317","鴻海"],["2303","聯電"],["2881","富邦金"],["2882","國泰金"],["2891","中信金"],["2886","兆豐金"],["2884","玉山金"],["2885","元大金"],["2892","第一金"],["5880","合庫金"],["2412","中華電"],["3045","台灣大"],["4904","遠傳"],["1301","台塑"],["1303","南亞"],["1326","台化"],["2002","中鋼"],["2603","長榮"],["2609","陽明"],["2615","萬海"],["2606","裕民"],["2618","長榮航"],["2610","華航"],["1216","統一"],["2912","統一超"],["2207","和泰車"],["2105","正新"],["1101","台泥"],["1102","亞泥"],["1402","遠東新"],["2357","華碩"],["2379","瑞昱"],["3034","聯詠"],["3008","大立光"],["3711","日月光投控"],["2345","智邦"],["2356","英業達"],["2376","技嘉"],["2377","微星"],["2324","仁寶"],["2353","宏碁"],["6669","緯穎"],["3661","世芯-KY"],["3443","創意"],["3017","奇鋐"]];
let P=JSON.parse(localStorage.ssa15p||"[]"),S=JSON.parse(localStorage.ssa11||'{"cash":100000,"h":[],"t":[],"r":0}');
const money=n=>"NT$"+Number(n).toLocaleString("zh-TW",{maximumFractionDigits:2}),save=()=>localStorage.ssa11=JSON.stringify(S),avg=a=>a.reduce((x,y)=>x+y,0)/a.length;
function months(){let d=new Date(),r=[];for(let i=0;i<3;i++){let x=new Date(d.getFullYear(),d.getMonth()-i,1);r.push(`${x.getFullYear()}${String(x.getMonth()+1).padStart(2,"0")}01`)}return r}
async function hist(code){let all=[];for(const date of months()){let u=`https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=${date}&stockNo=${code}&response=json`,r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error();let j=await r.json();(j.data||[]).forEach(z=>{let c=Number(String(z[6]).replace(/,/g,"")),v=Number(String(z[1]).replace(/,/g,""));if(c>0)all.push({date:z[0],close:c,vol:v})})}return [...new Map(all.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date))}
function calc(h){if(h.length<21)throw Error();let c=h.map(x=>x.close),v=h.map(x=>x.vol),last=c.at(-1),ma5=avg(c.slice(-5)),ma20=avg(c.slice(-20)),r5=(last/c.at(-6)-1)*100,r20=(last/c.at(-21)-1)*100,vr=avg(v.slice(-5))/Math.max(1,avg(v.slice(-20))),rets=c.slice(-20).map((x,i,a)=>i?Math.abs(x/a[i-1]-1)*100:0).slice(1),vo=avg(rets),score=50;score+=last>ma5?8:-8;score+=ma5>ma20?12:-12;score+=Math.max(-12,Math.min(12,r5*1.5));score+=Math.max(-12,Math.min(12,r20*.6));score+=vr>1.15?8:vr<.8?-5:0;score-=Math.max(0,(vo-3)*2);score=Math.max(0,Math.min(100,Math.round(score)));let tags=[];if(last>ma5&&ma5>ma20)tags.push("多頭趨勢");if(r5>0)tags.push("5日動能");if(r20>0)tags.push("20日動能");if(vr>1.15)tags.push("量能放大");if(!tags.length)tags.push("偏弱觀察");return{score,last,r5,r20,vr,ma5,ma20,tags}}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function scan(){scanBtn.disabled=true;scanBtn.textContent="掃描中…";P=[];let good=[],fail=0;
 for(let i=0;i<POOL.length;i++){let [code,name]=POOL[i];scanStatus.textContent=`正在分析 ${i+1} / ${POOL.length}：${name} ${code}`;bar.style.width=`${Math.round((i+1)/POOL.length*100)}%`;
  try{let h=await hist(code),x=calc(h),z=h.at(-1);good.push({code,name,score:x.score,price:x.last,date:z.date,tags:x.tags,why:`5日 ${x.r5.toFixed(1)}%｜20日 ${x.r20.toFixed(1)}%｜均線 ${x.ma5.toFixed(1)}/${x.ma20.toFixed(1)}｜量比 ${x.vr.toFixed(2)}`})}catch(e){fail++}
  if((i+1)%5===0)await wait(250);
 }
 P=good.sort((a,b)=>b.score-a.score).slice(0,5);localStorage.ssa15p=JSON.stringify(P);dataBadge.textContent="TWSE 自動篩選";scanStatus.textContent=`完成：成功分析 ${good.length} 檔，失敗 ${fail} 檔，顯示前 ${P.length} 檔`;dataNotice.textContent="Strategy v1.5：從預設 50 檔上市股候選池，以 TWSE 歷史日行情計算後取分數較高的 5 檔。這不是全市場掃描，也不是投資建議。";scanBtn.disabled=false;scanBtn.textContent="重新掃描 50 檔";render()}
function metrics(){let m=0,c=0;S.h.forEach(h=>{let s=P.find(x=>x.code==h.code);if(s){m+=s.price*h.qty;c+=h.cost}});let u=m-c,total=S.cash+m;return{u,total,p:total-BASE,rate:(total-BASE)/BASE*100}}
function buy(i){let s=P[i];if(S.cash<s.price)return alert("可用現金不足");S.cash-=s.price;let h=S.h.find(x=>x.code==s.code);h?(h.qty++,h.cost+=s.price):S.h.push({code:s.code,name:s.name,qty:1,cost:s.price});S.t.unshift({a:"買進",name:s.name,code:s.code,price:s.price,time:new Date().toLocaleString("zh-TW"),source:"TWSE收盤"});save();render()}
function sell(code){let h=S.h.find(x=>x.code==code),s=P.find(x=>x.code==code);if(!h||!s)return;let av=h.cost/h.qty,d=s.price-av;S.cash+=s.price;S.r+=d;h.qty--;h.cost-=av;S.t.unshift({a:"賣出",name:s.name,code,price:s.price,d,time:new Date().toLocaleString("zh-TW"),source:"TWSE收盤"});if(!h.qty)S.h=S.h.filter(x=>x.code!=code);save();render()}
function render(){list.innerHTML=P.length?P.map((s,i)=>`<article class="stock"><div class="head"><div><h3>${s.name} <span class="code">${s.code}</span></h3><div class="chips">${s.tags.map(x=>`<span class="chip">${x}</span>`).join("")}</div></div><div><div class="score">策略 ${s.score}</div><div class="price">${money(s.price)}</div><span class="label">TWSE 收盤價</span></div></div><div class="grid"><div><span class="label">資料日期</span><b>${s.date}</b></div><div><span class="label">行情</span><b>非即時收盤</b></div><div><span class="label">來源</span><b>TWSE</b></div><div><span class="label">策略版本</span><b>v1.5</b></div></div><p class="reason"><b>計算摘要：</b>${s.why}</p><button class="buy" onclick="buy(${i})">模擬買進 1 股</button></article>`).join(""):'<div class="empty">尚未有選股結果，請按「開始掃描 50 檔」。</div>';
 holds.innerHTML=S.h.length?S.h.map(h=>{let s=P.find(x=>x.code==h.code);let price=s?s.price:h.cost/h.qty,d=price*h.qty-h.cost;return`<article class="stock"><h3>${h.name} ${h.code}</h3><p>${h.qty} 股｜平均成本 ${money(h.cost/h.qty)}｜目前可計損益 <span class="${d>=0?"pos":"neg"}">${money(d)}</span></p>${s?`<button class="buy" onclick="sell('${h.code}')">模擬賣出 1 股</button>`:'<span class="label">本次精選無此股，暫用成本顯示</span>'}</article>`}).join(""):'<div class="empty">目前沒有持股</div>';
 tradeList.innerHTML=S.t.length?S.t.map(t=>`<div class="trade"><b>${t.a} ${t.name} ${t.code}</b><br>${money(t.price)}｜${t.time}<br><span class="label">${t.source||"舊版紀錄"}</span>${t.d!==undefined?`<br>已實現損益 ${money(t.d)}`:""}</div>`).join(""):'<div class="empty">目前沒有交易紀錄</div>';let x=metrics();asset.textContent=money(x.total);cash.textContent=money(S.cash);pnl.textContent=money(x.p);realized.textContent=money(S.r);unrealized.textContent=money(x.u);rate.textContent=x.rate.toFixed(2)+"%"}
scanBtn.onclick=scan;document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.panel").forEach(x=>x.classList.remove("on"));b.classList.add("on");document.getElementById(b.dataset.t).classList.add("on")});
if(P.length){dataBadge.textContent="上次掃描結果";scanStatus.textContent="已載入上次掃描的 5 檔結果，可按重新掃描更新。";scanBtn.textContent="重新掃描 50 檔"}render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=15");